GET http://localhost:3000/auth/login
Authorization: Basic cm9vdDpyb290

###

GET http://localhost:3000/auth/refresh-token
Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpYXQiOjE1Nzk5NTQ3MDAsImV4cCI6MTU3OTk1ODMwMH0.4QW750YLnjZ3UQVa_rxoxJOO9fPQQfsSUcovp1lkh9Y

###

POST http://localhost:3000/mdm/user
Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpYXQiOjE1ODUxNjEzNjksImV4cCI6MTU4NTE2MTk2OX0.o5pFQHKeMo4oBAXtEb6D2ymdlK4Msod3Hjc4GFQdrfA
Content-Type: application/json

{
  "firstname": "firstname",
  "lastname": "lastname",
  "email": "email@email.com",
  "dob": "2019-09-09"
}

###

GET http://localhost:3000/mdm/user
Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpYXQiOjE1ODUxNjEzNjksImV4cCI6MTU4NTE2MTk2OX0.o5pFQHKeMo4oBAXtEb6D2ymdlK4Msod3Hjc4GFQdrfA